import { supabaseAdmin } from '../config/supabase.js';
import { logAuditAction } from '../services/auditService.js';
import {
  getPendingUnclusteredComplaints,
  getClusterContextForPlanning,
} from '../services/agentBridge.js';

/**
 * AI Clustering Agent Endpoint:
 * Accepts grouped complaint IDs from the Gemini clusterer, persists or updates
 * root-cause clusters, links complaints, and recomputes the geographic centroid.
 * POST /api/v1/agent/clusters/sync
 */
export const syncCluster = async (req, res, next) => {
  try {
    const {
      cluster_id = null,
      root_cause_title,
      priority_score,
      summary,
      status = 'planning',
      complaint_ids,
    } = req.body;

    let targetCluster = null;

    // 1. Create or update complaint_cluster record
    if (cluster_id) {
      const { data: updatedCluster, error: updateError } = await supabaseAdmin
        .from('complaint_clusters')
        .update({
          root_cause_title,
          priority_score,
          summary,
          status,
        })
        .eq('id', cluster_id)
        .select()
        .single();

      if (updateError) {
        return next(updateError);
      }
      targetCluster = updatedCluster;
    } else {
      const { data: newCluster, error: createError } = await supabaseAdmin
        .from('complaint_clusters')
        .insert({
          root_cause_title,
          priority_score,
          summary,
          status,
        })
        .select()
        .single();

      if (createError) {
        return next(createError);
      }
      targetCluster = newCluster;
    }

    // 2. Link complaints to cluster and update their status to 'clustered'
    const { error: linkError } = await supabaseAdmin
      .from('complaints')
      .update({
        cluster_id: targetCluster.id,
        status: 'clustered',
      })
      .in('id', complaint_ids);

    if (linkError) {
      return next(linkError);
    }

    // 3. Recalculate PostGIS centroid via Postgres stored procedure
    const { error: centroidError } = await supabaseAdmin.rpc('recalculate_cluster_centroid', {
      p_cluster_id: targetCluster.id,
    });

    if (centroidError) {
      console.warn('⚠️ [AgentCentroid Warning] Could not recalculate centroid:', centroidError.message);
    }

    // 4. Audit logging for end-to-end provenance
    await logAuditAction({
      entityType: 'cluster',
      entityId: targetCluster.id,
      action: cluster_id ? 'CLUSTER_UPDATED_BY_AGENT' : 'CLUSTER_CREATED_BY_AGENT',
      performedBy: req.user?.id || null,
      metadata: {
        root_cause_title,
        priority_score,
        linked_complaints_count: complaint_ids.length,
        complaint_ids,
      },
    });

    return res.status(cluster_id ? 200 : 201).json({
      success: true,
      message: 'Complaints clustered and spatial centroid synchronized successfully.',
      data: {
        cluster: targetCluster,
        linked_complaints_count: complaint_ids.length,
      },
    });
  } catch (error) {
    return next(error);
  }
};

/**
 * AI Action Planner Agent Endpoint:
 * Accepts structured step-by-step resolution proposals generated by Gemini,
 * inserting them into action_plans marked with approval_status: 'pending'.
 * POST /api/v1/agent/action-plans
 */
export const createActionPlan = async (req, res, next) => {
  try {
    const {
      cluster_id,
      steps_json,
      assigned_department_id = null,
      requires_operator_approval = true,
      approval_status = 'pending',
      approval_notes = null,
      estimated_cost = null,
    } = req.body;

    // 1. Verify cluster exists
    const { data: cluster, error: clusterError } = await supabaseAdmin
      .from('complaint_clusters')
      .select('id, root_cause_title, status')
      .eq('id', cluster_id)
      .maybeSingle();

    if (clusterError) {
      return next(clusterError);
    }

    if (!cluster) {
      return res.status(404).json({
        success: false,
        error: {
          code: 'CLUSTER_NOT_FOUND',
          message: `Complaint cluster with ID "${cluster_id}" does not exist.`,
        },
      });
    }

    // 2. Insert action plan into public.action_plans
    const { data: actionPlan, error: insertError } = await supabaseAdmin
      .from('action_plans')
      .insert({
        cluster_id,
        steps_json,
        assigned_department_id,
        requires_operator_approval,
        approval_status,
        approval_notes,
        estimated_cost,
      })
      .select(`
        *,
        departments:assigned_department_id (
          id,
          name,
          contact_email,
          priority_level
        )
      `)
      .single();

    if (insertError) {
      return next(insertError);
    }

    // 3. Update cluster status
    const newClusterStatus = requires_operator_approval ? 'planning' : 'in_execution';
    await supabaseAdmin
      .from('complaint_clusters')
      .update({ status: newClusterStatus })
      .eq('id', cluster_id);

    // 4. Record audit provenance log
    await logAuditAction({
      entityType: 'action_plan',
      entityId: actionPlan.id,
      action: 'ACTION_PLAN_PROPOSED_BY_AGENT',
      performedBy: req.user?.id || null,
      metadata: {
        cluster_id,
        steps_count: steps_json.length,
        assigned_department_id,
        requires_operator_approval,
        approval_status,
        estimated_cost,
      },
    });

    return res.status(201).json({
      success: true,
      message: 'AI action plan submitted successfully and queued for operator review.',
      data: {
        action_plan: actionPlan,
      },
    });
  } catch (error) {
    return next(error);
  }
};

/**
 * AI Observation Fetch Endpoint:
 * Feeds unclustered, pending citizen complaints to the Gemini Clustering Agent
 * GET /api/v1/agent/pending-complaints
 */
export const getPendingComplaints = async (req, res, next) => {
  try {
    const limit = Number(req.query.limit) || 50;
    const category = req.query.category || null;
    const sinceHours = req.query.sinceHours ? Number(req.query.sinceHours) : null;

    const payload = await getPendingUnclusteredComplaints({ limit, category, sinceHours });

    return res.status(200).json({
      success: true,
      count: payload.length,
      data: {
        unclustered_complaints: payload,
      },
    });
  } catch (error) {
    return next(error);
  }
};

/**
 * AI Planner Context Fetch Endpoint:
 * Supplies cluster metadata, constituent complaints, and department list to Gemini Planner
 * GET /api/v1/agent/clusters/:clusterId/context
 */
export const getClusterContext = async (req, res, next) => {
  try {
    const { clusterId } = req.params;
    const context = await getClusterContextForPlanning(clusterId);

    return res.status(200).json({
      success: true,
      data: context,
    });
  } catch (error) {
    return next(error);
  }
};

export default {
  syncCluster,
  createActionPlan,
  getPendingComplaints,
  getClusterContext,
};
