import { z } from 'zod';

/**
 * Validation schema for syncing clusters generated by the AI Clusterer
 * POST /api/v1/agent/clusters/sync
 */
export const syncClusterBodySchema = z.object({
  cluster_id: z
    .string()
    .uuid({ message: 'cluster_id must be a valid UUID' })
    .optional()
    .nullable(),
  root_cause_title: z
    .string({ required_error: 'root_cause_title is required' })
    .trim()
    .min(3, { message: 'Title must be at least 3 characters long' })
    .max(200, { message: 'Title cannot exceed 200 characters' }),
  priority_score: z.coerce
    .number({ required_error: 'priority_score is required' })
    .min(0, { message: 'priority_score cannot be negative' })
    .max(10, { message: 'priority_score maximum value is 10.0' }),
  summary: z
    .string({ required_error: 'summary is required' })
    .trim()
    .min(5, { message: 'summary must be at least 5 characters long' })
    .max(3000, { message: 'summary cannot exceed 3000 characters' }),
  status: z
    .enum(['open', 'planning', 'in_execution', 'resolved', 'verified', 'escalated'])
    .default('planning'),
  complaint_ids: z
    .array(z.string().uuid({ message: 'Each complaint ID must be a valid UUID' }), {
      required_error: 'complaint_ids array is required',
    })
    .min(1, { message: 'complaint_ids array must contain at least 1 complaint UUID' }),
});

export const syncClusterSchema = {
  body: syncClusterBodySchema,
};

/**
 * Step schema within an AI Action Plan
 */
export const actionPlanStepSchema = z.object({
  order: z.number().int().positive({ message: 'Step order must be a positive integer' }),
  action: z.string().trim().min(3, { message: 'Action description is required' }),
  department: z.string().trim().optional(),
  sla_hours: z.number().positive().optional(),
  automated: z.boolean().default(false),
  equipment_needed: z.array(z.string().trim()).optional(),
  cost_estimate: z.number().nonnegative().optional(),
});

/**
 * Validation schema for submitting structured AI Action Plans
 * POST /api/v1/agent/action-plans
 */
export const createActionPlanBodySchema = z.object({
  cluster_id: z
    .string({ required_error: 'cluster_id is required' })
    .uuid({ message: 'cluster_id must be a valid UUID' }),
  steps_json: z
    .array(actionPlanStepSchema, { required_error: 'steps_json array is required' })
    .min(1, { message: 'Action plan must contain at least one step' }),
  assigned_department_id: z
    .string()
    .uuid({ message: 'assigned_department_id must be a valid UUID' })
    .optional()
    .nullable(),
  requires_operator_approval: z.boolean().default(true),
  approval_status: z
    .enum(['pending', 'pending_review', 'not_required', 'approved'])
    .default('pending'),
  approval_notes: z.string().trim().optional().nullable(),
  estimated_cost: z.number().nonnegative().optional().nullable(),
});

export const createActionPlanSchema = {
  body: createActionPlanBodySchema,
};

export default {
  syncClusterSchema,
  syncClusterBodySchema,
  createActionPlanSchema,
  createActionPlanBodySchema,
};
